import { StudentProfile, Subject, Topic, Exam, Goal, AIInsight, NotificationItem, DailyProgress, StudySession } from '../types';

export const INITIAL_PROFILE: StudentProfile = {
  id: 'profile-1',
  user_id: 'user-demo-1',
  full_name: 'Alex Kumar',
  email: 'alex.kumar@university.edu',
  college: 'Apex Institute of Technology',
  course: 'B.Tech in Computer Science',
  semester: 'Semester 5',
  daily_available_hours: 4,
  preferred_study_start_time: '18:00',
  preferred_study_end_time: '22:00',
  preferred_study_period: 'Evening',
  weekly_study_target_hours: 24,
  current_streak_days: 12,
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
  onboarding_completed: true,
};

// Calculate relative exam dates for realistic countdowns
const addDays = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'sub-dsa',
    user_id: 'user-demo-1',
    name: 'DSA',
    current_knowledge_percentage: 45,
    target_percentage: 90,
    difficulty: 'Hard',
    exam_date: addDays(5), // 5 days left as requested
    weekly_study_target_hours: 8,
    color: '#EF4444', // Red
    notes: 'Core foundation for campus placements and technical interviews.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-python',
    user_id: 'user-demo-1',
    name: 'Python',
    current_knowledge_percentage: 75,
    target_percentage: 95,
    difficulty: 'Easy',
    exam_date: addDays(22),
    weekly_study_target_hours: 4,
    color: '#3B82F6', // Blue
    notes: 'Data structures, OOP, async programming and FastAPI backend.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-math',
    user_id: 'user-demo-1',
    name: 'Mathematics',
    current_knowledge_percentage: 60,
    target_percentage: 85,
    difficulty: 'Hard',
    exam_date: addDays(12),
    weekly_study_target_hours: 5,
    color: '#F59E0B', // Amber
    notes: 'Probability, Linear Algebra, and Discrete Math structures.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-dbms',
    user_id: 'user-demo-1',
    name: 'DBMS',
    current_knowledge_percentage: 70,
    target_percentage: 88,
    difficulty: 'Medium',
    exam_date: addDays(18),
    weekly_study_target_hours: 4,
    color: '#10B981', // Emerald
    notes: 'Relational algebra, normalization (BCNF), indexing & ACID transactions.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-cloud',
    user_id: 'user-demo-1',
    name: 'Cloud Computing',
    current_knowledge_percentage: 40,
    target_percentage: 80,
    difficulty: 'Medium',
    exam_date: addDays(28),
    weekly_study_target_hours: 3,
    color: '#8B5CF6', // Purple
    notes: 'Virtualization, Docker, Kubernetes, AWS/GCP architecture.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_TOPICS: Topic[] = [
  // DSA topics
  {
    id: 'top-dsa-1',
    subject_id: 'sub-dsa',
    user_id: 'user-demo-1',
    name: 'Arrays, Two Pointers & Sliding Window',
    status: 'Completed',
    difficulty: 'Easy',
    estimated_duration_hours: 4,
    order_index: 1,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-dsa-2',
    subject_id: 'sub-dsa',
    user_id: 'user-demo-1',
    name: 'Binary Trees & BST Traversals',
    status: 'Completed',
    difficulty: 'Medium',
    estimated_duration_hours: 5,
    order_index: 2,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-dsa-3',
    subject_id: 'sub-dsa',
    user_id: 'user-demo-1',
    name: 'Graph Algorithms (BFS/DFS, Dijkstra)',
    status: 'In Progress',
    difficulty: 'Hard',
    estimated_duration_hours: 6,
    order_index: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-dsa-4',
    subject_id: 'sub-dsa',
    user_id: 'user-demo-1',
    name: 'Dynamic Programming (1D & 2D Knapsack)',
    status: 'Pending',
    difficulty: 'Hard',
    estimated_duration_hours: 8,
    order_index: 4,
    created_at: new Date().toISOString(),
  },

  // Python topics
  {
    id: 'top-py-1',
    subject_id: 'sub-python',
    user_id: 'user-demo-1',
    name: 'Advanced List Comprehensions & Generators',
    status: 'Completed',
    difficulty: 'Easy',
    estimated_duration_hours: 2,
    order_index: 1,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-py-2',
    subject_id: 'sub-python',
    user_id: 'user-demo-1',
    name: 'Object-Oriented Programming & Dunder Methods',
    status: 'Completed',
    difficulty: 'Medium',
    estimated_duration_hours: 3,
    order_index: 2,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-py-3',
    subject_id: 'sub-python',
    user_id: 'user-demo-1',
    name: 'Asyncio, Concurrency & Threading',
    status: 'In Progress',
    difficulty: 'Hard',
    estimated_duration_hours: 3,
    order_index: 3,
    created_at: new Date().toISOString(),
  },

  // Mathematics topics
  {
    id: 'top-m-1',
    subject_id: 'sub-math',
    user_id: 'user-demo-1',
    name: 'Matrix Operations & Eigenvalues',
    status: 'Completed',
    difficulty: 'Medium',
    estimated_duration_hours: 3,
    order_index: 1,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-m-2',
    subject_id: 'sub-math',
    user_id: 'user-demo-1',
    name: 'Conditional Probability & Bayes Theorem',
    status: 'In Progress',
    difficulty: 'Medium',
    estimated_duration_hours: 3,
    order_index: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-m-3',
    subject_id: 'sub-math',
    user_id: 'user-demo-1',
    name: 'Combinatorics & Recurrence Relations',
    status: 'Pending',
    difficulty: 'Hard',
    estimated_duration_hours: 4,
    order_index: 3,
    created_at: new Date().toISOString(),
  },

  // DBMS topics
  {
    id: 'top-db-1',
    subject_id: 'sub-dbms',
    user_id: 'user-demo-1',
    name: 'ER Modeling & Relational Schema Mapping',
    status: 'Completed',
    difficulty: 'Easy',
    estimated_duration_hours: 2.5,
    order_index: 1,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-db-2',
    subject_id: 'sub-dbms',
    user_id: 'user-demo-1',
    name: 'Complex SQL Queries, Joins & Views',
    status: 'Completed',
    difficulty: 'Medium',
    estimated_duration_hours: 3.5,
    order_index: 2,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-db-3',
    subject_id: 'sub-dbms',
    user_id: 'user-demo-1',
    name: 'Concurrency Control & Deadlock Handling',
    status: 'In Progress',
    difficulty: 'Hard',
    estimated_duration_hours: 3,
    order_index: 3,
    created_at: new Date().toISOString(),
  },

  // Cloud topics
  {
    id: 'top-cl-1',
    subject_id: 'sub-cloud',
    user_id: 'user-demo-1',
    name: 'Cloud Service Models (IaaS, PaaS, SaaS)',
    status: 'Completed',
    difficulty: 'Easy',
    estimated_duration_hours: 2,
    order_index: 1,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-cl-2',
    subject_id: 'sub-cloud',
    user_id: 'user-demo-1',
    name: 'Docker Containers & Multi-stage Builds',
    status: 'In Progress',
    difficulty: 'Medium',
    estimated_duration_hours: 4,
    order_index: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'top-cl-3',
    subject_id: 'sub-cloud',
    user_id: 'user-demo-1',
    name: 'Kubernetes Pods, Deployments & Services',
    status: 'Pending',
    difficulty: 'Hard',
    estimated_duration_hours: 5,
    order_index: 3,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    name: 'DSA Mid-Term Exam',
    exam_date: addDays(5),
    exam_time: '10:00 AM',
    location: 'Hall 302, Academic Block A',
    syllabus_coverage_percentage: 100,
    target_score: 90,
    notes: 'Focus on Graph algorithms and Dynamic Programming recurrence trees.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exam-2',
    user_id: 'user-demo-1',
    subject_id: 'sub-math',
    name: 'Discrete Math & Probability',
    exam_date: addDays(12),
    exam_time: '02:00 PM',
    location: 'Science Auditorium',
    syllabus_coverage_percentage: 85,
    target_score: 85,
    notes: 'Formulas cheat sheet review on morning of exam.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exam-3',
    user_id: 'user-demo-1',
    subject_id: 'sub-dbms',
    name: 'DBMS Final Theory Paper',
    exam_date: addDays(18),
    exam_time: '09:30 AM',
    location: 'Hall 105',
    syllabus_coverage_percentage: 95,
    target_score: 88,
    notes: 'Include normalization proofs and B+ Tree diagrams.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exam-4',
    user_id: 'user-demo-1',
    subject_id: 'sub-python',
    name: 'Python Lab & Viva Assessment',
    exam_date: addDays(22),
    exam_time: '11:00 AM',
    location: 'Computer Lab 4',
    syllabus_coverage_percentage: 100,
    target_score: 95,
    notes: 'Prepare GitHub portfolio repository demonstration.',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    title: 'Complete DSA before September 20',
    description: 'Master arrays, trees, graphs, and DP before the mid-term paper.',
    target_metric: 'Finish 100% syllabus topics',
    current_progress_percentage: 45,
    deadline: '2026-09-20',
    is_completed: false,
    category: 'Subject Mastery',
    created_at: new Date().toISOString(),
  },
  {
    id: 'goal-2',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    title: 'Solve 60 LeetCode Practice Questions',
    description: 'Build algorithmic intuition under timed mock conditions.',
    target_metric: '60 medium problems solved',
    current_progress_percentage: 72,
    deadline: '2026-09-30',
    is_completed: false,
    category: 'Exam Prep',
    created_at: new Date().toISOString(),
  },
  {
    id: 'goal-3',
    user_id: 'user-demo-1',
    subject_id: 'sub-python',
    title: 'Build Full-Stack FastAPI Project',
    description: 'Apply async programming and relational database modeling.',
    target_metric: 'Deploy live API on cloud',
    current_progress_percentage: 80,
    deadline: '2026-10-10',
    is_completed: false,
    category: 'Project',
    created_at: new Date().toISOString(),
  },
  {
    id: 'goal-4',
    user_id: 'user-demo-1',
    title: 'Maintain 21-Day Daily Study Streak',
    description: 'Study at least 2.5 hours every single evening without interruption.',
    target_metric: '21 continuous days logged',
    current_progress_percentage: 57,
    deadline: '2026-09-25',
    is_completed: false,
    category: 'Daily Habit',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ai-1',
    user_id: 'user-demo-1',
    title: 'Urgent Exam Alert: DSA Exam in 5 Days',
    summary: 'Your current syllabus coverage for DSA stands at 45%, while your target score is 90%.',
    recommendation: 'Prioritize Dynamic Programming and Graphs tonight. Allocate 2.5 hours from your 18:00 study window.',
    subject_name: 'DSA',
    impact_level: 'High',
    action_label: 'Start DSA Sprint',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ai-2',
    user_id: 'user-demo-1',
    title: 'Study Load Rebalancing Recommendation',
    summary: 'Python progress is strong at 75%. You have completed 2 out of 3 core syllabus modules.',
    recommendation: 'Temporarily shift 1.5 weekly hours from Python towards Mathematics probability proofs.',
    subject_name: 'Python',
    impact_level: 'Medium',
    action_label: 'Adjust Weekly Targets',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ai-3',
    user_id: 'user-demo-1',
    title: 'Peak Cognitive Retention Window',
    summary: 'Your logged study sessions show 94% focus efficiency between 18:30 and 21:00.',
    recommendation: 'Schedule difficult theoretical subjects (DBMS normal forms & discrete math) during this golden window.',
    impact_level: 'Low',
    action_label: 'View Schedule Planner',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'user-demo-1',
    title: 'Exam Approaching: DSA Mid-Term in 5 Days',
    message: 'Data Structures & Algorithms Mid-Term Exam is scheduled for ' + addDays(5) + ' at 10:00 AM. 4 syllabus topics remain incomplete.',
    type: 'exam',
    is_read: false,
    read: false,
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-session-today',
    user_id: 'user-demo-1',
    title: 'Study Session Approaching Tonight',
    message: 'Scheduled block "DSA Trees & Traversal" starts at 18:00 (75 mins). Optimal retention window detected.',
    type: 'session',
    is_read: false,
    read: false,
    created_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-risk-dsa',
    user_id: 'user-demo-1',
    title: 'High-Risk Subject Alert: DSA',
    message: 'DSA may not reach the 90% target before the exam at your current study pace. Increase daily study time by 30 minutes.',
    type: 'risk',
    is_read: false,
    read: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-weekly-audit',
    user_id: 'user-demo-1',
    title: 'Weekly Academic Report Ready',
    message: 'Your Monday → Sunday performance report is generated. You achieved 82% of planned study hours with +16% improvement.',
    type: 'report',
    is_read: false,
    read: false,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-pending-task',
    user_id: 'user-demo-1',
    title: 'Pending High-Difficulty Task',
    message: 'Topic "Dynamic Programming – 0/1 Knapsack" (Hard, ~4h duration) is pending before upcoming exam cutoff.',
    type: 'task',
    is_read: false,
    read: false,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-deadline-goal',
    user_id: 'user-demo-1',
    title: 'Academic Deadline: Semester Project Viva',
    message: 'Full-Stack Web Dev Portfolio milestone deadline is in 14 days. 65% completed so far.',
    type: 'deadline',
    is_read: true,
    read: true,
    created_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'user-demo-1',
    title: 'Streak Milestone: 12 Days Strong!',
    message: 'Great consistency! You have logged study sessions for 12 consecutive days across all subjects.',
    type: 'streak',
    is_read: true,
    read: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-goal-done',
    user_id: 'user-demo-1',
    title: 'Goal Milestone Achieved!',
    message: 'You fulfilled your target for Python Fundamentals! 100% syllabus mastery logged.',
    type: 'goal',
    is_read: true,
    read: true,
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_DAILY_PROGRESS: DailyProgress[] = [
  { id: 'dp-1', user_id: 'user-demo-1', date: '2026-09-04', study_minutes: 240, target_minutes: 240, topics_completed: 2, efficiency_score: 88 },
  { id: 'dp-2', user_id: 'user-demo-1', date: '2026-09-05', study_minutes: 190, target_minutes: 240, topics_completed: 1, efficiency_score: 82 },
  { id: 'dp-3', user_id: 'user-demo-1', date: '2026-09-06', study_minutes: 260, target_minutes: 240, topics_completed: 3, efficiency_score: 92 },
  { id: 'dp-4', user_id: 'user-demo-1', date: '2026-09-07', study_minutes: 220, target_minutes: 240, topics_completed: 2, efficiency_score: 85 },
  { id: 'dp-5', user_id: 'user-demo-1', date: '2026-09-08', study_minutes: 270, target_minutes: 240, topics_completed: 2, efficiency_score: 90 },
  { id: 'dp-6', user_id: 'user-demo-1', date: '2026-09-09', study_minutes: 210, target_minutes: 240, topics_completed: 1, efficiency_score: 87 },
  { id: 'dp-7', user_id: 'user-demo-1', date: '2026-09-10', study_minutes: 150, target_minutes: 240, topics_completed: 1, efficiency_score: 89 },
];

export const INITIAL_STUDY_SESSIONS: StudySession[] = [
  // Today's sessions
  {
    id: 'sess-today-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    topic_id: 'top-dsa-1',
    title: 'DSA – Binary Trees & Traversal Techniques',
    session_date: addDays(0),
    start_time: '18:00',
    end_time: '19:15',
    duration_minutes: 75,
    planned_duration_minutes: 75,
    actual_duration_minutes: 75,
    status: 'Completed',
    efficiency_rating: 5,
    notes: 'Level order traversal and recursive subtree height calculations.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sess-today-2',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    topic_id: 'top-dsa-2',
    title: 'DSA – Dijkstra & Shortest Path Algorithms',
    session_date: addDays(0),
    start_time: '19:30',
    end_time: '20:45',
    duration_minutes: 75,
    planned_duration_minutes: 75,
    status: 'Planned',
    notes: 'Priority queue implementation and edge relaxation mechanics.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sess-today-3',
    user_id: 'user-demo-1',
    subject_id: 'sub-dbms',
    topic_id: 'top-dbms-1',
    title: 'DBMS – Normalization & 3NF / BCNF',
    session_date: addDays(0),
    start_time: '21:00',
    end_time: '22:00',
    duration_minutes: 60,
    planned_duration_minutes: 60,
    status: 'Planned',
    notes: 'Lossless join decomposition and dependency preservation.',
    created_at: new Date().toISOString(),
  },
  // Tomorrow's sessions (Day + 1)
  {
    id: 'sess-day1-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    topic_id: 'top-dsa-3',
    title: 'DSA – Graph Traversals BFS & DFS Practice',
    session_date: addDays(1),
    start_time: '18:00',
    end_time: '19:30',
    duration_minutes: 90,
    planned_duration_minutes: 90,
    status: 'Planned',
    notes: 'Cycle detection in directed and undirected graphs.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sess-day1-2',
    user_id: 'user-demo-1',
    subject_id: 'sub-python',
    topic_id: 'top-py-2',
    title: 'Python – Asyncio Event Loop & FastAPI Endpoints',
    session_date: addDays(1),
    start_time: '19:45',
    end_time: '20:45',
    duration_minutes: 60,
    planned_duration_minutes: 60,
    status: 'Planned',
    notes: 'Async database sessions and benchmark test runs.',
    created_at: new Date().toISOString(),
  },
  // Day + 2
  {
    id: 'sess-day2-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    topic_id: 'top-dsa-4',
    title: 'DSA – Dynamic Programming Memoization Sprint',
    session_date: addDays(2),
    start_time: '18:00',
    end_time: '19:30',
    duration_minutes: 90,
    planned_duration_minutes: 90,
    status: 'Planned',
    notes: '0/1 Knapsack problem and Longest Common Subsequence.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sess-day2-2',
    user_id: 'user-demo-1',
    subject_id: 'sub-math',
    topic_id: 'top-math-1',
    title: 'Mathematics – Conditional Probability & Bayes Theorem',
    session_date: addDays(2),
    start_time: '19:45',
    end_time: '21:00',
    duration_minutes: 75,
    planned_duration_minutes: 75,
    status: 'Planned',
    notes: 'Prior and posterior distribution calculations.',
    created_at: new Date().toISOString(),
  },
  // Day + 3 (Revision before DSA exam in 5 days)
  {
    id: 'sess-day3-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    title: 'DSA – Final Mock & Exam Revision Sprint',
    session_date: addDays(3),
    start_time: '18:00',
    end_time: '19:30',
    duration_minutes: 90,
    planned_duration_minutes: 90,
    status: 'Planned',
    is_revision: true,
    notes: 'High-frequency LeetCode mediums and time complexity drills.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sess-day3-2',
    user_id: 'user-demo-1',
    subject_id: 'sub-dbms',
    topic_id: 'top-dbms-2',
    title: 'DBMS – Transaction ACID Properties & Concurrency',
    session_date: addDays(3),
    start_time: '19:45',
    end_time: '21:00',
    duration_minutes: 75,
    planned_duration_minutes: 75,
    status: 'Planned',
    notes: 'Two-phase locking protocol and conflict serializability.',
    created_at: new Date().toISOString(),
  },
  // Day + 4 (Day before DSA Exam)
  {
    id: 'sess-day4-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    title: 'DSA – Intensive Problem Marathon & Formula Review',
    session_date: addDays(4),
    start_time: '18:00',
    end_time: '19:30',
    duration_minutes: 90,
    planned_duration_minutes: 90,
    status: 'Planned',
    is_revision: true,
    notes: 'Quick revision of algorithm bounds and edge cases before tomorrow’s exam.',
    created_at: new Date().toISOString(),
  },
  // Past sessions (Yesterday)
  {
    id: 'sess-past-1',
    user_id: 'user-demo-1',
    subject_id: 'sub-dsa',
    title: 'DSA – Heaps & Priority Queues',
    session_date: addDays(-1),
    start_time: '18:00',
    end_time: '19:30',
    duration_minutes: 90,
    planned_duration_minutes: 90,
    actual_duration_minutes: 90,
    status: 'Completed',
    efficiency_rating: 5,
    notes: 'Min-heap and max-heap array conversions.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sess-past-2',
    user_id: 'user-demo-1',
    subject_id: 'sub-python',
    title: 'Python – Decorators & Generators',
    session_date: addDays(-1),
    start_time: '19:45',
    end_time: '20:45',
    duration_minutes: 60,
    planned_duration_minutes: 60,
    actual_duration_minutes: 60,
    status: 'Completed',
    efficiency_rating: 4,
    notes: 'Custom timing decorators and memory efficient yield expressions.',
    created_at: new Date().toISOString(),
  },
];

